package vcTris;
/**
 *
 * @author Vittorio Privitera
 */
public class MainGame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGame.class.getName());
    /**
     * Creates new form MainGame
     */
    public MainGame() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        difficoltà = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        b1_btn = new javax.swing.JButton();
        b2_btn = new javax.swing.JButton();
        b3_btn = new javax.swing.JButton();
        b4_btn = new javax.swing.JButton();
        b5_btn = new javax.swing.JButton();
        b6_btn = new javax.swing.JButton();
        b7_btn = new javax.swing.JButton();
        b8_btn = new javax.swing.JButton();
        b9_btn = new javax.swing.JButton();
        bInizia_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        username_txt = new javax.swing.JTextField();
        finisci_btn = new javax.swing.JButton();
        rivedi_btn = new javax.swing.JButton();
        bottoMedio_btn = new javax.swing.JRadioButton();
        bottoFacile_btn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        tempo_lbl = new javax.swing.JLabel();
        record_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("---TRIS---");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(219, 219, 219))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        b1_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vuoto.png"))); // NOI18N
        b1_btn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        b1_btn.setMaximumSize(new java.awt.Dimension(100, 100));
        b1_btn.setMinimumSize(new java.awt.Dimension(100, 100));
        b1_btn.setPreferredSize(new java.awt.Dimension(100, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel4.add(b1_btn, gridBagConstraints);

        b2_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vuoto.png"))); // NOI18N
        b2_btn.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel4.add(b2_btn, new java.awt.GridBagConstraints());

        b3_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vuoto.png"))); // NOI18N
        b3_btn.setPreferredSize(new java.awt.Dimension(100, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel4.add(b3_btn, gridBagConstraints);

        b4_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vuoto.png"))); // NOI18N
        b4_btn.setPreferredSize(new java.awt.Dimension(100, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel4.add(b4_btn, gridBagConstraints);

        b5_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vuoto.png"))); // NOI18N
        b5_btn.setPreferredSize(new java.awt.Dimension(100, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel4.add(b5_btn, gridBagConstraints);

        b6_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vuoto.png"))); // NOI18N
        b6_btn.setPreferredSize(new java.awt.Dimension(100, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel4.add(b6_btn, gridBagConstraints);

        b7_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vuoto.png"))); // NOI18N
        b7_btn.setPreferredSize(new java.awt.Dimension(100, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel4.add(b7_btn, gridBagConstraints);

        b8_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vuoto.png"))); // NOI18N
        b8_btn.setToolTipText("");
        b8_btn.setPreferredSize(new java.awt.Dimension(100, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel4.add(b8_btn, gridBagConstraints);

        b9_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vuoto.png"))); // NOI18N
        b9_btn.setPreferredSize(new java.awt.Dimension(100, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel4.add(b9_btn, gridBagConstraints);

        bInizia_btn.setBackground(new java.awt.Color(153, 153, 255));
        bInizia_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bInizia_btn.setForeground(new java.awt.Color(255, 255, 255));
        bInizia_btn.setText("START");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Username:");

        username_txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        finisci_btn.setBackground(new java.awt.Color(153, 153, 255));
        finisci_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        finisci_btn.setForeground(new java.awt.Color(255, 255, 255));
        finisci_btn.setText("FINISH");

        rivedi_btn.setBackground(new java.awt.Color(153, 153, 255));
        rivedi_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rivedi_btn.setForeground(new java.awt.Color(255, 255, 255));
        rivedi_btn.setText("REPLAY");

        difficoltà.add(bottoMedio_btn);
        bottoMedio_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bottoMedio_btn.setText("MEDIO");

        difficoltà.add(bottoFacile_btn);
        bottoFacile_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bottoFacile_btn.setText("FACILE");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("DIFFICOLTA'");

        tempo_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tempo_lbl.setText("0");

        record_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        record_lbl.setText("Record ?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(tempo_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bInizia_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finisci_btn)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rivedi_btn)
                            .addComponent(bottoFacile_btn)
                            .addComponent(bottoMedio_btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(147, 147, 147)
                        .addComponent(record_lbl)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bInizia_btn)
                    .addComponent(finisci_btn)
                    .addComponent(tempo_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(record_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(bottoMedio_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rivedi_btn)
                                .addGap(197, 197, 197))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bottoFacile_btn)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1_btn;
    private javax.swing.JButton b2_btn;
    private javax.swing.JButton b3_btn;
    private javax.swing.JButton b4_btn;
    private javax.swing.JButton b5_btn;
    private javax.swing.JButton b6_btn;
    private javax.swing.JButton b7_btn;
    private javax.swing.JButton b8_btn;
    private javax.swing.JButton b9_btn;
    private javax.swing.JButton bInizia_btn;
    private javax.swing.JRadioButton bottoFacile_btn;
    private javax.swing.JRadioButton bottoMedio_btn;
    private javax.swing.ButtonGroup difficoltà;
    private javax.swing.JButton finisci_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel record_lbl;
    private javax.swing.JButton rivedi_btn;
    private javax.swing.JLabel tempo_lbl;
    private javax.swing.JTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
